version: '2'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: dockerized-laravel-app/app
    volumes:
     - .:/var/www/html
    networks:
     - appnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: dockerized-laravel-app/node
    volumes:
     - .:/var/www/html
    networks:
     - appnet
  mysql:
    image: mysql:5.7
    volumes:
     - mysqldata:/var/lib/mysql
    networks:
     - appnet
  redis:
    image: redis:alpine
    volumes:
     - redisdata:/data
    networks:
     - appnet